version: 1
disable_existing_loggers: False
formatters:
  main:
    format: '%(asctime)s - %(levelname)s - %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
handlers:
  console:
    class: logging.StreamHandler
    formatter: main
    stream: ext://sys.stdout  
    level: INFO
root:
  level: INFO
  handlers: [console]